// Exports contract ABIs from Foundry's build output into abi/index.ts, which the API imports.
// The generated file is committed so the app never needs Foundry to build.
// Usage: node scripts/export-abi.mjs [--check]   (run `forge build` first)
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const contracts = ["KudosToken", "CreativeRegistry"];

let out = "// Generated by scripts/export-abi.mjs from Foundry build output. Do not edit by hand.\n";
for (const name of contracts) {
  const artifact = JSON.parse(readFileSync(join(root, "out", `${name}.sol`, `${name}.json`), "utf8"));
  const exportName = name.charAt(0).toLowerCase() + name.slice(1) + "Abi";
  out += `\nexport const ${exportName} = ${JSON.stringify(artifact.abi, null, 2)} as const;\n`;
}

const target = join(root, "abi", "index.ts");
if (process.argv.includes("--check")) {
  const current = readFileSync(target, "utf8");
  if (current !== out) {
    console.error("abi/index.ts is out of date. Run `pnpm --filter @skaddosh/contracts abi` and commit it.");
    process.exit(1);
  }
  console.log("abi/index.ts is up to date.");
} else {
  writeFileSync(target, out);
  console.log(`Wrote ${target}`);
}
